# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qlqFO30zI-hBY4EbvVQ6QJ69pfMr_0nU
"""

import pandas as pd
import random

from google.colab import files
files.upload()

df=pd.read_csv("countries.csv")

countries = df["COUNTRIES"].tolist()
continents = df["CONTINENTS"].tolist()

print("HELLO, Would you like to play a game !!!\n")
name = input("What is your name ?\n")
print("Instructions :")
print("\nYour task is to guess the country name. You are given with total letters of the country.")
print("If you get stuck you have 2 hints. You can choose ONLY ONE.")
print("So choose wisely.")
print("If you guess 5 wrong alpabets then you will lose.\n")
print("Let's start the game",name,"\n")
country = random.choice(countries)
print("Total letters of the country are",len(country))
print("Start Guessing the alphabets of the country.")
print("Do you want a hint ?\n")
choice = int(input("Enter 1 for YES and 0 for NO  "))
if(choice == 1):
  print("Hint 1 : First letter of the country.\n")
  print("Hint 2: Continent in which country is situated.\n")
  c = int(input(""))
  if(c == 1):
    print(country[0])
  else:
    index=countries.index(country)
    print(continents[index])

else:
  print("Continue with the game.\n")

fail = 0
li=[]
correct_list = []
for word in country:
  li.append(word)
correct_list = ['_' for i in range(len(li))]
while(correct_list.count('_') != 0):
    alpha = input("\nEnter a character : ").upper()
    for i in range(len(li)):
       letter = li[i]
       if (letter == alpha):
          correct_list[i] = alpha
    for j in correct_list:
      print(j,end = " ")
    if(alpha not in li):
        print("\nWrong answer")
        fail+=1
    if(fail == 5):
      print("Country was",country)
      print("\nYou lost,Better luck next time.\n")
      break
    if(correct_list == li):
      print("\nCongrats!!, You guessed the country!!")
      print("Country is",country)
      break

